name: Apply Terraform Unity Catalog

on:
  workflow_call:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - name: Apply Terraform Unity Catalog
      run: |
        cd shared/unity-catalog
        terraform plan --var-file="../../configs/commons/unity-catalog.tfvars"
        terraform apply --var-file="../../configs/commons/unity-catalog.tfvars" -auto-approve