name: Creating Infrastructure with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, pre, prod]

    env:
      # Azure environment variables
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}"
          echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          echo "AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}"

      - uses: ./setup-terraform.yml

      - uses: ./init-terraform.yml

      - uses: ./apply-terraform-unity-catalog.yml

      - uses: ./apply-environments.yml

      - name: Print workflow context
        run: |
          echo "Workflow context:"
          echo "  Event: $GITHUB_EVENT_NAME"
          echo "  Action: $GITHUB_ACTION"
          echo "  Workflow: $GITHUB_WORKFLOW"
          echo "  Repository: $GITHUB_REPOSITORY"
          echo "  Branch: $GITHUB_REF"