name: Setup Terraform

on:
  workflow_call:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '~> 1.9'