name: Terraform

on:
  push:
    branches:
      - working-poc-v2
  pull_request:
    branches:
      - working-poc-v2

jobs:
  terraform:
    name: Execute Terraform
    runs-on: ubuntu-latest
    env:
      # Azure environment variables
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Navigate to /shared/unity-catalog and run Terraform Apply
        run: |
          cd shared/unity-catalog
          terraform init
          terraform plan --var-file="../../configs/commons/unity-catalog.tfvars"
          terraform apply --var-file="../../configs/commons/unity-catalog.tfvars" -auto-approve
      
      - name: Navigate to /workspace/ws-datalake and create workspaces
        run: |
          cd workspace/ws-datalake
          terraform workspace new dev || true
          terraform workspace new pre || true
          terraform workspace new prod || true

      - name: Select workspace and apply Terraform for all environments
        run: |
          cd workspace/ws-datalake
          
          for env in dev pre prod; do
            terraform workspace select $env
            terraform init
            terraform plan --var-file="../../configs/environments/$env.tfvars"
            terraform apply --var-file="../../configs/environments/$env.tfvars" -auto-approve
          done