name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    env:
        # Set Environment Variables at Job level
        # Databricks environment variables
        # DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
        # DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

        # Azure environment variables
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6  # Use the appropriate Terraform version

    - name: Navigate to /shared/unity-catalog and run Terraform Init
      run: |
        cd shared/unity-catalog
        terraform init

    - name: Navigate to /shared/unity-catalog and run Terraform Plan
      run: |
        cd shared/unity-catalog
        terraform plan --var-file="../../configs/commons/unity-catalog.tfvars"
        terraform apply --var-file="../../configs/commons/unity-catalog.tfvars" -auto-approve
      
    - name: Navigate to /workspace/ws-datalake and create workspaces
      run: |
        cd workspace/ws-datalake
        terraform workspace new dev || true
        terraform workspace new pre || true
        terraform workspace new prod || true

    - name: Select workspace and apply Terraform for DEV Env
      run: |
        cd workspace/ws-datalake
        terraform workspace select dev
        terraform init
        terraform plan --var-file="../../configs/environments/dev.tfvars"
        terraform apply --var-file="../../configs/environments/dev.tfvars" -auto-approve
        
        # Uncomment these lines to create and apply configurations for other environments
        terraform workspace select pre
        terraform init
        terraform plan --var-file="../../configs/environments/pre.tfvars"
        terraform apply --var-file="../../configs/environments/pre.tfvars" -auto-approve
        
        terraform workspace select prod
        terraform init
        terraform plan --var-file="../../configs/environments/prod.tfvars"
        terraform apply --var-file="../../configs/environments/prod.tfvars" -auto-approve
      
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    # - name: Navigate to /workspace/ws-datalake and run Terraform Output
    #   run: |
    #     cd workspace/ws-datalake
    #     terraform output
